- hosts: localhost
  connection: local
  gather_facts: no
  sudo: no
  roles:
    - profile
    - homebrew
    - homebrew-cask
    - vagrant-plugins
    - post-setup
    - cron-setup
  vars:
    # Tap external Homebrew repositories.
    #
    # e.g.
    # - homebrew/binary
    homebrew_repositories:
      - ethereum/ethereum

    # Managed Homebrew packages.
    #
    # e.g.
    # - package_name
    # or
    # { name: package_name, state: package_state, install_options: [with-baz, enable-debug] }
    #
    # state choices: [head, latest, present, absent, linked, unlinked] (default: latest)
    # install_options: string or sequence (default: none)
    homebrew_packages:
      - readline
      - openssl
      - { name: openssl, state: linked, install_options: force }
      - ansible
      - git
#      - git-flow
#      - heroku-toolbelt
#      - peco
#      - nvm
#      - rbenv
#      - ruby-build
#      - the_silver_searcher
      - vim
      - zsh
      - zsh-completions
      - zsh-syntax-highlighting
      - mysql
      - postgresql
      - tree
      - wget
      - curl
      - nodebrew
      - jenkins
      - maven
      - ant
      - apache-spark 
      - hadoop 
      - kafka 
      - zookeeper 
      - scala 
      - ghc 
      - p7zip 
      - gradle 
      - cabal-install 
      - ocaml 
      - git-flow 
      - rabbitmq 
      - python 
      - mercurial 
      - kotlin 
      - cmake 
      - pandoc 
      - { name: yarn, install_options: --without-node }
      - go 
      - ethereum 
      - elasticsearch 
      - kibana 
      - redis 
      - solidity 
      - kubectl 
      - sbt 

    # Tap external Homebrew Cask repositories.
    homebrew_cask_repositories:
      - caskroom/versions

    # Managed Homebrew Cask packages.
    #
    # e.g.
    # - package_name
    # or
    # { name: package_name, state: package_state }
    #
    # state choices: [present, absent, installed, uninstalled] (default: present)
    homebrew_cask_packages:
#      - alfred
#      - firefox
      - google-chrome
#      - google-japanese-ime
#      - iterm2
      - intellij-idea
      - eclipse-platform
      - java
#      - karabiner
#      - phpstorm
#      - rubymine
#      - slack
#      - sublime-text
      - kobito
      - vagrant
      - virtualbox
      - kindle
      - spectacle
      - dropbox
      - skype
      - citrix-receiver
      - astah-community
      - gimp
      - android-studio
      - xquartz
      - atom

