---
   - name: List Installed Vagrant Plugins
     shell: "vagrant plugin list | awk '{ print $1 }'"
     changed_when: false
     register: vagrant_plugin_list

   - name: Install Vagrant Plugins
     shell: "vagrant plugin install {{item}}"
     with_items:
       - sahara
       - vagrant-hostmanager
     when: item not in vagrant_plugin_list.stdout_lines
  
